# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d98637cb0af23e5db3e7a624d0d95733cd9874fd8beeef6d1c8b08a45c546b70366b9ea41c487e6f69b3e850c1438845851dc5beceada3b74b1a1a5ca09791

test:
  secret_key_base: 95fa07878a263a34fe91a7547037e5fa230c5477b0c1042b7391336b148956747efa4f53fc0a80057149f00613762ca6bd1f6357a9d1ea32285ec02de59161dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
